/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.HomeController', {
    extend: 'Ext.app.Controller',

    onBtnSearchBookingClick: function(button, e, eOpts) {

    },

    init: function(application) {
        this.control({
            "#btnSearchBooking": {
                click: this.onBtnSearchBookingClick
            }
        });
    }

});
