/*
 * File: app/controller/LoginControllers.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.controller.LoginControllers', {
    extend: 'Ext.app.Controller',

    onBtnLoginClick: function(button, e, eOpts) {
        var loginInfo = Ext.ModelManager.getModel('layout.model.loginInfo');
        loginInfo.set('username', 'hello');
        loginInfo.set('password', 'hello');

        Ext.Ajax.request({
            url : 'login',
            method : 'POST',
            jsonData :  Ext.encode(user),
            success : function(response) {
                var res = Ext.decode(result.responseText);
            },
            failure : function(result, request) {
                var jsonn = '{isSuccess: "true",role: "userkoto",userId: 123}';
                var res = Ext.decode(jsonn);
                /*	var user = Ext.create('loginInfo',[{
                isSuccess : "true",
                role : "rolekoto",
                userId : "123"
                },{
                isSuccess : "false",
                role : "rolekotos",
                userId : "23"
                }]);*/
                console.log(res);
                console.log("Update function ajax request failed");
            }
        });


        this.vpHome = Ext.create('layout.view.com.grp1.bkg.vpHome');
        this.vpHome.show();
    },

    init: function(application) {
        this.control({
            "#btnLogin": {
                click: this.onBtnLoginClick
            }
        });
    }

});
