/*
 * File: app/view/com/grp1/bkg/vpLogin.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('layout.view.com.grp1.bkg.vpLogin', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Spacer',
        'Ext.button.Button'
    ],

    id: 'com.grp1.bkg.vpLogin',
    itemId: 'com.grp1.bkg.vpLogin',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'vbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'form',
                            height: 211,
                            id: 'com.grp1.miniproj.frmLogin',
                            maxHeight: 250,
                            maxWidth: 500,
                            width: 363,
                            autoScroll: true,
                            bodyPadding: 10,
                            title: 'Login',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    height: 82,
                                    layout: {
                                        type: 'vbox',
                                        align: 'center',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'txtUsername',
                                            itemId: 'txtUsername',
                                            fieldLabel: 'Username:',
                                            listeners: {
                                                click: {
                                                    fn: me.onlblUsernameClick,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'txtPassword',
                                            itemId: 'txtPassword',
                                            fieldLabel: 'Password'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    items: [
                                        {
                                            xtype: 'tbspacer',
                                            width: 18
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 0,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            height: 30,
                                            id: 'btnLogin',
                                            itemId: 'btnLogin',
                                            width: 100,
                                            text: 'Login'
                                        },
                                        {
                                            xtype: 'tbspacer',
                                            flex: 1,
                                            width: 18
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            height: 30,
                                            itemId: 'btnCancel',
                                            width: 100,
                                            text: 'Cancel'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onlblUsernameClick: function(textfield) {

    }

});